In [1]:
# -*- coding: utf-8 -*-
"""
Created on Thu Jul 16 18:30:23 2020

@author: AAA
"""

import pandas as pd
import numpy as np
import math

data=pd.read_csv('./Zhongxing财务_删0_label0.01_forVisual_afterMerge.csv',encoding='utf-8')
data.head()
df=pd.DataFrame()

date=[]
close=[]
pred=[]

for i in range(len(data)-1):
    date.append(data.iloc[i, 2])
    close.append(data.iloc[i, 3])
    if data.iloc[i, 0] > 0.5:
        pred.append(data.iloc[i, 3] + abs(data.iloc[i, 3]-data.iloc[i+1, 3]))
    else:
        pred.append(data.iloc[i, 3] - abs(data.iloc[i, 3]-data.iloc[i+1, 3]))

df['DATE']=date
df['CLOSE']=close
df['PRED']=pred

df.to_csv('./test_visual_2.csv', encoding='utf-8', index=False)

TypeError: '>' not supported between instances of 'str' and 'float'

In [2]:
data

,date,open,high,low,close,volume,increase,increaserate,change,PE,PB,A-index,communicaiton-index,label
0,2019/12/31,1.714463,1.835326,1.772659,1.807365,1.468128,1.512936,1.048862,1.321340,-1.231183,2.649029,0.625625,1.209613,1
1,2019/12/30,1.563958,1.635896,1.620334,1.679237,0.572969,1.034191,0.723837,0.450549,-1.206559,2.499741,0.604564,1.177234,1
2,2019/12/27,1.641678,1.593593,1.656842,1.591764,0.165550,-0.373027,-0.295999,0.054214,-1.189762,2.397912,0.569795,1.148642,0
3,2019/12/26,1.613304,1.565794,1.650547,1.623797,-0.169186,0.221777,0.133328,-0.271346,-1.195835,2.434729,0.595649,1.192476,1
4,2019/12/25,1.508443,1.585132,1.572497,1.605316,0.504461,0.918132,0.649979,0.384092,-1.192287,2.413213,0.568312,1.183548,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1723,2010/2/25,3.244193,3.131013,3.198969,3.109596,-0.870782,0.163747,0.060852,-0.782763,1.002473,1.628793,-0.589399,-0.646816,1
1724,2010/2/24,2.837088,3.029486,2.915721,3.096044,-0.843659,2.760573,1.507958,-0.721304,0.999128,1.619084,-0.633709,-0.656165,1
1725,2010/2/9,2.710022,2.641505,2.714301,2.672234,-0.913123,-0.851772,-0.510449,-0.875630,0.880096,1.273439,-0.754176,-0.789734,0
1726,2010/2/5,2.664376,2.657217,2.726889,2.707962,-0.856580,-0.431057,-0.271438,-0.745616,0.888810,1.298760,-0.761706,-0.786151,0
1727,2010/2/4,2.633535,2.659635,2.690382,2.744922,-0.856093,1.164758,0.647675,-0.744505,0.897822,1.324936,-0.711030,-0.777406,1